name: Terraform DCM Plan

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        type: choice
        options:
          - DEV
          - TEST

permissions:
  id-token: write
  contents: read

jobs:

  terraform-plan:

    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}-Terraform

    defaults:
      run:
        working-directory: terraform/environments/dev

    env:
      TF_SNOWFLAKE_ACCOUNT: ${{ vars.TF_SNOWFLAKE_ACCOUNT }}
      TF_SNOWFLAKE_ORGANIZATION: ${{ vars.TF_SNOWFLAKE_ORGANIZATION }}
      TERRAFORM_USER: ${{ vars.TERRAFORM_USER }}
      TERRAFORM_ROLE: ${{ vars.TERRAFORM_ROLE }}

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: Get GitHub OIDC Token
        id: oidc
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken('snowflakecomputing.com');
            core.setOutput('token', token);

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
          SNOWFLAKE_TOKEN: ${{ steps.oidc.outputs.token }}
        run: |
          terraform plan \
            -var="snowflake_account=${TF_SNOWFLAKE_ACCOUNT}" \
            -var="snowflake_organization=${TF_SNOWFLAKE_ORGANIZATION}" \
            -var="terraform_user=${TERRAFORM_USER}" \
            -var="terraform_role=${TERRAFORM_ROLE}"

  dcm-plan:
    runs-on: ubuntu-latest
    
    

    environment:
        name: ${{ inputs.environment }}-DCM
    
    env:
       SNOWFLAKE_ACCOUNT: ${{ vars.SNOWFLAKE_ACCOUNT }}
       SNOWFLAKE_USER: ${{ vars.DCM_USER }}
   
    steps:

    - uses: actions/checkout@v4

    - uses: snowflakedb/snowflake-actions@v3
      with:
        use-oidc: true
    - name: Test DCM Connection
      run: |
        snow connection test -x \
          --account $SNOWFLAKE_ACCOUNT \
          --user $SNOWFLAKE_USER \
          --authenticator WORKLOAD_IDENTITY \
          --workload-identity-provider OIDC
    
    - name: Create Connection
      run: |
        snow connection add \
          --connection-name github \
          --account $SNOWFLAKE_ACCOUNT \
          --user $SNOWFLAKE_USER \
          --authenticator WORKLOAD_IDENTITY \
          --workload-identity-provider OIDC \
          --default \
          --no-interactive



    - name: Verify Connection
      run: |
        snow connection test -x \
          --account $SNOWFLAKE_ACCOUNT \
          --user $SNOWFLAKE_USER \
          --authenticator WORKLOAD_IDENTITY \
          --workload-identity-provider OIDC

    - name: List Connections
      run: |
        snow connection list

    - name: DCM Plan
      run: |
        snow dcm plan \
          --account $SNOWFLAKE_ACCOUNT \
          --user $SNOWFLAKE_USER \
          --authenticator WORKLOAD_IDENTITY \
          --workload-identity-provider OIDC \
          --target DEV      